In [ ]:
import numpy as np

###### Arrays in NumPy

In [2]:
# creating array object
arr=np.array([[1,2,3],[4,2,5]])

print("Array is of type: ",type(arr))
print("No. of dimensions: ",arr.ndim)
print("Shape of array: ",arr.shape)
print("Size of array: ",arr.size)
print("Array stores elements of type: ",arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


##### Array creation

In [3]:
# creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print("Array created using passed list:\n", a)

# creating array from tuple
b = np.array((1 , 3, 2))
print("\nArray created using passed tuple:\n", b)

# creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print("\nAn array initialized with all zeros:\n", c)

# creating a 3X4 array with all ones
d=np.ones((3,4))
print("\nAn array initialized with all ones:\n", d)

#create a 2-D array with ones on the diagonal and zeros elsewhere
e=np.eye(3)
print("\nAn array having diagonal elements as one:\n", e)

# create a constant value array of complex type
f = np.full((3, 3), 6, dtype = 'complex')
print("\nAn array initialized with all 6s. Array type is complex:\n", f)

# create an array with random values
g = np.random.random((2,2))
print("\nA random array:\n", g)

# create a sequence of integers from 0 to 30 with steps of 5
h = np.arange(0, 30, 5)
print("\nA sequential array with steps of 5:\n", h)

# create a sequence of 10 values in range 0 to 5
i = np.linspace(0, 5, 10)
print("\nA sequential array with 10 values between 0 and 5:\n", i)

# reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
newarr = arr.reshape(2, 2, 3)
print("\nOriginal array:\n", arr)
print("Reshaped array:\n", newarr)

# flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()
print("\nOriginal array:\n", arr)
print("Fattened array:\n", flarr)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]

Array created using passed tuple:
 [1 3 2]

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

An array initialized with all ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

An array having diagonal elements as one:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

An array initialized with all 6s. Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]

A random array:
 [[0.65545852 0.6502315 ]
 [0.95551753 0.88736731]]

A sequential array with steps of 5:
 [ 0  5 10 15 20 25]

A sequential array with 10 values between 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


##### Array Indexing

In [4]:
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2]])
print("\nOriginal array:\n", arr)

#slicing
temp=arr[1:,:3:2]
print("Array with last 3 rows and alternate columns(0 and 2):\n", temp)

# integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print("\nElements at indices (0, 3), (1, 2), (2, 1), (3, 0):\n", temp)

# boolean array indexing example(cond is a boolean array)
cond = arr > 0    
temp = arr[cond]
print("\nElements greater than 0:\n", temp)


Original array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array with last 3 rows and alternate columns(0 and 2):
 [[4.  6. ]
 [2.6 7. ]
 [3.  4. ]]

Elements at indices (0, 3), (1, 2), (2, 1), (3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


##### Basic operations

In [5]:
a=np.array([1,2,5,3])

# add 1 to every element
print("Adding 1 to every element:", a+1)

# multiply each element by 3
print("Multiplying each element by 3:", a*3)

# modify existing array
a *= 2
print("Doubled each element of original array:", a)

# transpose of array 
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print("\nOriginal array:\n", a)
print("Transpose of array:\n", a.T)

Adding 1 to every element: [2 3 6 4]
Multiplying each element by 3: [ 3  6 15  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


##### Unary operators

In [6]:
arr = np.array([[1,5,6],[4,7,2],[3,1,9]])

# maximum element of array
print("Largest element is:", arr.max())
print("Row-wise maximum elements:", arr.max(axis = 1))

# minimum element of array
print("Column-wise minimum elements:", arr.min(axis = 0))

# sum of array elements
print("Sum of all array elements:", arr.sum())

# cumulative sum along each row
print("Cumulative sum along each row:\n", arr.cumsum(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


##### Binary operators

In [7]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,3],[2,1]])

# add arrays
print("Array sum:\n", a + b)

# multiply arrays
print("Array multiplication:\n", a*b)

# matrix multiplication
print("Matrix multiplication:\n", a.dot(b))

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


##### Universal functions

In [8]:
# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print("Sine values of array elements:", np.sin(a))

# exponential values
a = np.array([0, 1, 2, 3])
print("Exponent of array elements:", np.exp(a))

# square root of array values
print("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


##### Sorting arrays

In [9]:
a = np.array([[1,4,2],[3,4,6],[0,-1,5]])

# sorted array
print("Array elements in sorted order:\n",np.sort(a,axis = None))

# sort array row-wise
print("Row-wise sorted array:\n",np.sort(a,axis = 1))

# specify sort algorithm
print("Column wise sort by applying merge-sort:\n", np.sort(a, axis = 0, kind = 'mergesort'))

# example to show sorting of structured array
## set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

## values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

## creating array
arr = np.array(values, dtype = dtypes)
print("\nArray sorted by names:\n", np.sort(arr, order = 'name'))
print("Array sorted by grauation year and then cgpa:\n", np.sort(arr, order = ['grad_year', 'cgpa']))

Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]

Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by grauation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


##### Stacking and Splitting

In [10]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

# vertical stacking
print("Vertical stacking:\n",np.vstack((a,b)))

# horizontal stacking
print("\nHorizontal stacking:\n",np.hstack((a,b)))

c = [5,6]

# stacking columns
print("\nColumn stacking:\n", np.column_stack((a,c)))

# concatenation method 
print("\nConcatenating to 2nd axis:\n", np.concatenate((a,b),1))
d = np.array([[1,3,5,7,9,11],[2,4,6,8,10,12]])

# horizontal splitting
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(d,2))

# vertical splitting
print("\nSplitting along vertical axis into 2 parts:\n", np.vsplit(d,2))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]

Column stacking:
 [[1 2 5]
 [3 4 6]]

Concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]
Splitting along horizontal axis into 2 parts:
 [array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]

Splitting along vertical axis into 2 parts:
 [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


##### Numpy functions(Statistics)

In [11]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))

#Specify axis for the direction in case of multidim array
print(np.min(a,axis=0))
print(np.min(a,axis=1))

b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)
print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

c = np.array([1,5,4,2,0])
print(np.median(c))

# Mean vs Average is Weighted
print(np.mean(c))

# Weights 
w = np.array([1,1,1,1,1])
print(np.average(c,weights=w))

# weighted mean => n1*w1 + n2*w2 / n1+n2 
# Standard Deviation
d = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-d)**2))
print(myStd)

#Inbuilt Function
e = np.std(c)
print(e)

#Variance
print(myStd**2)
print(np.var(c))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]
3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]
2.0
2.4
2.4
1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004


##### Numpy Random Module

In [12]:
a = np.arange(10) + 5
print(a)

np.random.seed(1)
np.random.shuffle(a)
print(a)

#Returns values from a Standard Normal Distributions
b = np.random.randn(2,3)
print(b)

c = np.random.randint(5,10,3)
print(c)

#Randoly pick one element from a array
element = np.random.choice([1,4,3,2,11,27])
print(element)

[ 5  6  7  8  9 10 11 12 13 14]
[ 7 14 11  9  5  8  6 12 13 10]
[[ 1.5827523  -1.04514683  0.25759352]
 [-1.9593946  -1.50780766 -0.31529207]]
[7 9 6]
4
