# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
print(np.__config__.show())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Mypc/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Mypc/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Mypc/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\li

#### 3. Create a null vector of size 10

In [3]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array

In [4]:
n=np.zeros((4,4))
print("%d bytes"%(n.size*n.itemsize))

128 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [5]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [6]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [7]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [8]:
a=np.arange(10,50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [10]:
x=np.array([1,2,0,0,4,0])
for i in range(len(x)):
    if(x[i]!=0):
        print(i)

0
1
4


#### 11. Create a 3x3 identity matrix

In [11]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [12]:
np.random.random((3,3,3))

array([[[0.5387738 , 0.22296989, 0.99122102],
        [0.03628435, 0.71827562, 0.92550726],
        [0.68066839, 0.27237697, 0.43535336]],

       [[0.44694124, 0.26265131, 0.78559237],
        [0.10999854, 0.16562196, 0.08839509],
        [0.62082807, 0.03218166, 0.51801725]],

       [[0.04909273, 0.19818259, 0.86573241],
        [0.73131346, 0.45456423, 0.52590956],
        [0.52060377, 0.37483258, 0.6695281 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [13]:
a=np.random.random((10,10))
print(a)
print('The maximum value is {}' .format(a.max()),'The minimum value is {}'.format(a.min()),sep='\n')

[[0.87827218 0.74215896 0.16007438 0.84655332 0.30668593 0.19275994
  0.45322242 0.6441113  0.59813231 0.41629495]
 [0.0576858  0.51646262 0.30708763 0.81969643 0.11039258 0.91968783
  0.84909365 0.29843813 0.35674075 0.63470356]
 [0.80136671 0.12845292 0.9168555  0.56208579 0.25698815 0.90414485
  0.89890329 0.32819916 0.74750396 0.12813319]
 [0.23535755 0.26743459 0.27715997 0.09624194 0.29047513 0.59358
  0.2354913  0.63163494 0.4533699  0.97644796]
 [0.77898051 0.909699   0.99322305 0.58627289 0.19924473 0.3853371
  0.66232169 0.25206508 0.8958721  0.26226524]
 [0.04123824 0.56998722 0.27139012 0.27761612 0.95588558 0.71089083
  0.02805731 0.61521755 0.36793522 0.34100134]
 [0.57148042 0.7543746  0.64841812 0.85666008 0.18564393 0.82539156
  0.08114974 0.09729041 0.54999114 0.5835957 ]
 [0.88212429 0.96130956 0.21176267 0.56096565 0.36697837 0.10667718
  0.23749437 0.60154791 0.90120301 0.3624837 ]
 [0.42935436 0.26467372 0.89842771 0.29433229 0.75579177 0.34290317
  0.65356279 0.6

#### 14. Create a random vector of size 30 and find the mean value

In [14]:
a=np.random.random(30)
print(a)
print('The mean value is {}' .format(a.mean()))

[0.39281429 0.76675166 0.5201921  0.97378296 0.96844591 0.87613726
 0.14719673 0.23307847 0.35778635 0.21243649 0.19801126 0.9379793
 0.86208346 0.07100845 0.41314266 0.32365128 0.77490662 0.09331201
 0.76709876 0.0385505  0.53232144 0.23972451 0.72707531 0.83948174
 0.38799917 0.44596725 0.30877099 0.21338283 0.26071741 0.21673792]
The mean value is 0.47001816969264915


#### 15. Create a 2d array with 1 on the border and 0 inside

In [15]:
a=np.ones((3,3))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [16]:
a=np.ones((3,3))
a=np.pad(a,pad_width=1,constant_values=0)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [18]:
a=np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [19]:
a=np.zeros((8,8),dtype=int)
a[1::2,::2]=1
a[::2,1::2]=1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
print (np.unravel_index(100,(6,7,8)))

(1, 5, 4)
